revert "Merge 54464 - When we get a silent TCP RST, SPDY connections need to retry." in the 472 branch because it breaks the compile :
error: no type named ParamType in class net::SpdyNetworkTransactionTest

TBR:mbelshe
Review URL: http://codereview.chromium.org/3043040