gclient: Revert r52941's changes to gclient_scm.py.
This looks like it broke syncing from git repos:

  File "/home/derat/local/depot_tools/gclient.py", line 1208, in <module>
    sys.exit(Main(sys.argv[1:]))
  File "/home/derat/local/depot_tools/gclient.py", line 1198, in Main
    return command(parser, argv[1:])
  File "/home/derat/local/depot_tools/gclient.py", line 1035, in CMDsync
    return client.RunOnDeps('update', args)
  File "/home/derat/local/depot_tools/gclient.py", line 621, in RunOnDeps
    scm.RunCommand(command, self._options, args, file_list)
  File "/home/derat/local/depot_tools/gclient_scm.py", line 115, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/home/derat/local/depot_tools/gclient_scm.py", line 264, in update
    print_error=False)
  File "/home/derat/local/depot_tools/scm.py", line 84, in Capture
    return gclient_utils.CheckCall(c, in_directory, print_error)
  File "/home/derat/local/depot_tools/gclient_utils.py", line 58, in CheckCall
    raise CheckCallError(command, cwd, process.returncode, std_out, std_err)
gclient_utils.CheckCallError: (['git', 'fetch', 'origin', 'cc1c63d'],
'/usr/local/google/home/derat/chrome/src/third_party/cros', 128, '', "fatal:
Couldn't find remote ref cc1c63d\nfatal: The remote end hung up unexpectedly\n")

BUG=none
TEST=works again after the revert
Review URL: http://codereview.chromium.org/2888023