Fix dupe line causing Linux official builder error.
Linux official builders are failing with:
test_expectations.py:364 ERROR Line:642 More specific entry on line 642
overrides line 20 svg/css/composite-shadow-text.svg

This updates the fix in r81732 which removed the dupe for Windows, but
by leaving the line without the platform, caused Linux to have a dupe
because of the svg/css/composite-shadow-text.svg line in
test_expectations_chrome.txt.

BUG=
TEST=Linux official builders run webkit_tests again.

Review URL: http://codereview.chromium.org/6879048