Fix Mac Breakpad glue compilation error:
breakpad_mac.mm:137: error: 'parsed_command_line' was not declared in this scope

since r31143

BUG=none
TEST=Breakpad-enabled build should, um, build
Review URL: http://codereview.chromium.org/374011