Remove --use_sqlite.
Using this with the GAE SDK on my Linux box causes an
OperationalError: cannot commit transaction.

BUG=none
TEST=can use the chromium-status app locally
Review URL: http://codereview.chromium.org/3281004