Since revision 41449 InspectorResource is defined as class. Before that it had been declared as struct. See  http://trac.webkit.org/changeset/41449
In our forked version of InspectorConroller it's still defined as struct which conflicts with the rest of WebCore classes and may lead to compilation errors like below if CachedResource.h and InspectorController.h are imported in a single file:

c:\chrome\src\third_party\webkit\webcore\loader\CachedResource.h(42) : error C2220: warning treated as error - no 'object' file generated
c:\chrome\src\third_party\webkit\webcore\loader\CachedResource.h(42) : warning C4099: 'WebCore::InspectorResource' : type name first seen using 'struct' now seen using 'class'
        C:\chrome\src\third_party\WebKit\WebCore\inspector\InspectorController.h(80) : see declaration of 'WebCore::InspectorResource'
c:\chrome\src\third_party\webkit\webcore\loader\CachedResource.h(51) : warning C4099: 'WebCore::InspectorResource' : type name first seen using 'struct' now seen using 'class'
        C:\chrome\src\third_party\WebKit\WebCore\inspector\InspectorController.h(80) : see declaration of 'WebCore::InspectorResource'
 

Review URL: http://codereview.chromium.org/45064